language: ruby

dist: bionic

rvm:
  - 2.5
  - 2.6
  - 2.7
  - ruby-head

addons:
  firefox: latest

branches:
  only:
    - master
    - cucumber5

services:
  - xvfb

gemfile:
  - gemfiles/rails_6_0.gemfile
  - gemfiles/rails_5_2.gemfile

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head

before_install:
  - gem install --remote bundler -v '~> 1.17'
  - bin/install_geckodriver.sh
  - bin/install_webpacker.sh
